import { Rajdhani } from "next/font/google";
import "../css/globals.css";
import Drawer from "@/components/layout/drawer/Drawer";
import Sidebar from "@/components/layout/sidebar/Sidebar";

const geistMono = Rajdhani({
  subsets: ["latin"],
  variable: "--geist-mono-font",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistMono.className} bg-black relative`}>
      <body className={`${geistMono.variable} antialiased flex flex-col lg:flex-row max-w-[1920px] mx-auto px-4 lg:px-6 xl:px-12 gap-6 justify-between h-screen overflow-hidden`}>
        {/* Background Video */}
        <video className="fixed top-0 left-0 w-full h-full object-cover -z-10" autoPlay loop muted playsInline preload="auto">
          <source src="/asset/Bg-Video/video5.mp4" type="video/mp4" />
        </video>

        {/* Drawer */}
        <div className="z-50 absolute right-1/32 top-1/20">
          <Drawer />
        </div>

        {/* Gradient Box */}
        <div className="flex items-center justify-center">
          <div className="w-full h-96 lg:w-80 xl:w-96 lg:h-[550px] xl:h-[750px] glassyBg rounded-2xl">
            <Sidebar />
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
